# Generated by Django 5.2.5 on 2025-09-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_admin_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='ticket_files/'),
        ),
    ]
