# Generated by Django 5.2.5 on 2025-09-03 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticket_ticket_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_no',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
