# Generated by Django 5.2.5 on 2025-09-03 13:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_alter_ticket_ticket_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='access_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
